apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Backend configuration
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  
  # Frontend configuration
  API_URL: "http://api.social-dashboard.example.com"
